# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Wisielec.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from WisielecWpiszHaslo import *

class Ui_MainWindow(object):

    def openWindowWpiszHaslo(self):
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_FormHaslo()
        self.ui.setupUi(self.window)
        self.window.show()
        MainWindow.hide()

    def closeMainWindow(self):
        sys.exit(app.exec_())


class Gracz:
    pseudonim = "null"
    przegrane = 0
    wygrane = 0
    istnieje = 0
    rola = False # false jezeli zgaduje, true jezeli daje haslo
    def __init__(self,przegrane,wygrane,rola,pseudonim,istnieje):
        self.pseudonim=pseudonim
        self.przegrane=przegrane
        self.rola=rola
        self.wygrane=wygrane
        self.istnieje=istnieje

gracz1 = Gracz(0, 0, False,  "null",0)
gracz2 = Gracz(0, 0, False, "null",0)



class Ui_MainWindow(object):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1127, 643)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.przycisk_Graj = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.openWindowWpiszHaslo())
        self.przycisk_Graj.setEnabled(True)
        self.przycisk_Graj.setGeometry(QtCore.QRect(460, 360, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.przycisk_Graj.setFont(font)
        self.przycisk_Graj.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.przycisk_Graj.setObjectName("przycisk_Graj")
        self.przycisk_Wyjdz = QtWidgets.QPushButton(self.centralwidget,clicked = lambda: self.closeMainWindow())
        self.przycisk_Wyjdz.setEnabled(True)
        self.przycisk_Wyjdz.setGeometry(QtCore.QRect(460, 480, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.przycisk_Wyjdz.setFont(font)
        self.przycisk_Wyjdz.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.przycisk_Wyjdz.setObjectName("przycisk_Wyjdz")
        self.przycisk_Wyjdz.clicked.connect(self.closeMainWindow)
        self.przycisk_gracz1_potwierdz = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.utworzenie_gracza_1())
        self.przycisk_gracz1_potwierdz.setEnabled(True)
        self.przycisk_gracz1_potwierdz.setGeometry(QtCore.QRect(17, 100, 156, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.przycisk_gracz1_potwierdz.setFont(font)
        self.przycisk_gracz1_potwierdz.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.przycisk_gracz1_potwierdz.setObjectName("przycisk_gracz1_potwierdz")
        self.przycisk_gracz2_potwierdz = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.utworzenie_gracza_2())
        self.przycisk_gracz2_potwierdz.setEnabled(True)
        self.przycisk_gracz2_potwierdz.setGeometry(QtCore.QRect(958, 100, 156, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.przycisk_gracz2_potwierdz.setFont(font)
        self.przycisk_gracz2_potwierdz.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.przycisk_gracz2_potwierdz.setObjectName("przycisk_gracz2_potwierdz")
        self.nick_gracza1 = QtWidgets.QLabel(self.centralwidget)
        self.nick_gracza1.setGeometry(QtCore.QRect(20, 0, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.nick_gracza1.setFont(font)
        self.nick_gracza1.setObjectName("nick_gracza1")
        self.nick_gracza2 = QtWidgets.QLabel(self.centralwidget)
        self.nick_gracza2.setGeometry(QtCore.QRect(1040, 0, 71, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.nick_gracza2.setFont(font)
        self.nick_gracza2.setObjectName("nick_gracza2")
        self.przycisk_zamien_role = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.zamiana_rol(gracz1,gracz2))
        self.przycisk_zamien_role.setEnabled(True)
        self.przycisk_zamien_role.setGeometry(QtCore.QRect(460, 420, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.przycisk_zamien_role.setFont(font)
        self.przycisk_zamien_role.setCursor(QtGui.QCursor(QtCore.Qt.ClosedHandCursor))
        self.przycisk_zamien_role.setObjectName("przycisk_zamien_role")
        self.input_gracz1 = QtWidgets.QTextEdit(self.centralwidget)
        self.input_gracz1.setGeometry(QtCore.QRect(20, 40, 151, 31))
        self.input_gracz1.setObjectName("input_gracz1")
        self.input_gracz2 = QtWidgets.QTextEdit(self.centralwidget)
        self.input_gracz2.setGeometry(QtCore.QRect(960, 40, 151, 31))
        self.input_gracz2.setObjectName("input_gracz2")
        self.gracz1_rola = QtWidgets.QLabel(self.centralwidget)
        self.gracz1_rola.setEnabled(True)
        self.gracz1_rola.setGeometry(QtCore.QRect(20, 90, 151, 51))
        self.gracz1_rola.setText("")
        self.gracz1_rola.setObjectName("gracz1_rola")
        self.gracz1_wygrane = QtWidgets.QLabel(self.centralwidget)
        self.gracz1_wygrane.setEnabled(True)
        self.gracz1_wygrane.setGeometry(QtCore.QRect(20, 160, 151, 51))
        self.gracz1_wygrane.setText("")
        self.gracz1_wygrane.setObjectName("gracz1_wygrane")
        self.gracz1_przegrane = QtWidgets.QLabel(self.centralwidget)
        self.gracz1_przegrane.setEnabled(True)
        self.gracz1_przegrane.setGeometry(QtCore.QRect(20, 230, 151, 51))
        self.gracz1_przegrane.setText("")
        self.gracz1_przegrane.setObjectName("gracz1_przegrane")
        self.gracz2_przegrane = QtWidgets.QLabel(self.centralwidget)
        self.gracz2_przegrane.setEnabled(True)
        self.gracz2_przegrane.setGeometry(QtCore.QRect(970, 220, 151, 51))
        self.gracz2_przegrane.setText("")
        self.gracz2_przegrane.setObjectName("gracz2_przegrane")
        self.gracz2_wygrane = QtWidgets.QLabel(self.centralwidget)
        self.gracz2_wygrane.setEnabled(True)
        self.gracz2_wygrane.setGeometry(QtCore.QRect(970, 150, 151, 51))
        self.gracz2_wygrane.setText("")
        self.gracz2_wygrane.setObjectName("gracz2_wygrane")
        self.gracz2_rola = QtWidgets.QLabel(self.centralwidget)
        self.gracz2_rola.setEnabled(True)
        self.gracz2_rola.setGeometry(QtCore.QRect(970, 80, 151, 51))
        self.gracz2_rola.setText("")
        self.gracz2_rola.setObjectName("gracz2_rola")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1127, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Wisielec"))
        self.przycisk_Graj.setText(_translate("MainWindow", "GRAJ"))
        self.przycisk_Wyjdz.setText(_translate("MainWindow", "WYJDZ"))
        self.nick_gracza1.setText(_translate("MainWindow", "Gracz 1"))
        self.nick_gracza2.setText(_translate("MainWindow", "Gracz 2"))
        self.przycisk_zamien_role.setText(_translate("MainWindow", "ZAMIEN ROLE"))
        self.przycisk_gracz1_potwierdz.setText(_translate("MainWindow", "Potwierdz"))
        self.przycisk_gracz2_potwierdz.setText(_translate("MainWindow", "Potwierdz"))




    def utworzenie_gracza_1(self):
        gracz1.rola=False
        gracz1.pseudonim = self.input_gracz1.toPlainText()
        gracz1.istnieje=1
        self.nick_gracza1.setText(gracz1.pseudonim)



        print("git")
        return gracz1
    def utworzenie_gracza_2(self):

        gracz2.rola = True
        gracz2.pseudonim = self.input_gracz2.toPlainText()
        gracz2.istnieje = 1
        self.nick_gracza2.setText(gracz2.pseudonim)



        print("git")

        return gracz2
    def zamiana_rol(self,gracz1,gracz2):
        if gracz1.istnieje==1 and gracz2.istnieje==1:
            gracz_temp=gracz1
            gracz1=gracz2
            gracz2=gracz_temp
            self.nick_gracza1.setText(gracz1.pseudonim)
            self.nick_gracza2.setText(gracz2.pseudonim)
            print(gracz1.rola)
            print(gracz2.rola)




if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
