# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WisielecWybierzHaslo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget

import WisielecWpiszHaslo
import WisielecWybierzTemat

class Ui_Form(object):


    def __init__(self, gracz1, gracz2):
        self.gracz1 = gracz1
        self.gracz2 = gracz2
        print(self.gracz1.pseudonim)
        print(self.gracz2.pseudonim)
        print(self.gracz1.rola)
        print(self.gracz2.rola)

    def zmienOkno (self, nazwaOkna):
        if (nazwaOkna == "API"):
            self.window = QWidget()
            self.ui = WisielecWybierzTemat.Ui_Form(self.gracz1, self.gracz2)
            self.ui.setupUi(self.window)
            self.window.show()
            current_window = QtWidgets.QApplication.activeWindow()
            current_window.close()
        if(nazwaOkna == "WPISZ"):
            self.window = QWidget()
            self.ui = WisielecWpiszHaslo.Ui_FormHaslo(self.gracz1, self.gracz2)
            self.ui.setupUi(self.window)
            self.window.show()
            current_window = QtWidgets.QApplication.activeWindow()
            current_window.close()


    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(600, 250)
        self.API_buton = QtWidgets.QPushButton(Form, clicked=lambda: self.zmienOkno("API"))
        self.API_buton.setGeometry(QtCore.QRect(10, 80, 271, 131))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.API_buton.setFont(font)
        self.API_buton.setObjectName("API_buton")
        self.Wpisz_button = QtWidgets.QPushButton(Form, clicked=lambda: self.zmienOkno("WPISZ"))
        self.Wpisz_button.setGeometry(QtCore.QRect(300, 80, 271, 131))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.Wpisz_button.setFont(font)
        self.Wpisz_button.setObjectName("Wpisz_button")
        self.labelInstrukcja = QtWidgets.QLabel(Form)
        self.labelInstrukcja.setGeometry(QtCore.QRect(80, 20, 461, 41))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.labelInstrukcja.setFont(font)
        self.labelInstrukcja.setObjectName("labelInstrukcja")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.API_buton.setText(_translate("Form", "GENERUJ"))
        self.Wpisz_button.setText(_translate("Form", "WPISZ "))
        self.labelInstrukcja.setText(_translate("Form", "Wybierz sposób wybrania hasła"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
